### ISSUE TITLE
Prácticas para el libro disponibles

### ISSUE THREAD

**Issue by alx741** [gwolf/sistop#16]
Para la asignatura de `Sistemas Operativos 1` en la "Universidad de Cuenca" (Ecuador) se usó este grandioso libro en el semestre recientemente finalizado.

Fue necesario diseñar algunas prácticas que permitieran a los estudiantes ejercitar su conocimiento e investigar información relevante.

Pensé que quizás seria útil disponer de estas prácticas en el libro mismo, aunque siendo que fueron diseñadas para un curso universitario en una modalidad especifica podrían o no resultar adecuados para ser agregadas directamente al libro. En caso de que no, por favor cerrar este _issue_ con libertad.

Las prácticas en cuestión con los PDF generados: https://github.com/alx741/sistop_practicas

**Comment by gwolf** [comment]
¡Guau! ¡Qué buena contribución! :-D ¡Muchas gracias!
Revisando el material... Lo que mencionas es correcto, fueron diseñados para un curso en particular, y emplean ciertas herramientas en particular... Creo yo que lo más correcto sería no tenerlos como parte del libro, sino como un recurso lateral, como las diapositivas que tengo, o incluso viéndolo hacia alguna edición futura, como un tomo adicional de recursos para el docente, ¿te parece?
Entonces, si te parece, podríamos agregar al árbol principal un directorio "practicas", y dentro de éste, el material que me muestras.
Como detalle de estilo, yo preferiría que en el proyecto no entren los binarios generados (los PDFs), sino únicamente sus fuentes. Pon eso, mas un README indicando que la autoría original del directorio es tuya, en un "pull request" y lo incorporo.
Obviamente, si haces esta contribución y te interesa que te agregue al proyecto "primario" (con acceso de escritura  al Git, pues) para que puedas mantenerlo sin mediar pull requests o esas cosas, lo hago con todo gusto.

**Comment by alx741** [comment]
Me parece perfecto, era justamente lo que pensaba.

> yo preferiría que en el proyecto no entren los binarios generados (los PDFs), sino únicamente sus fuentes.

Excelente, puse los PDFs en el ultimo commit para poder ver las practicas sin tener que compilar, pero es mucho mejor que no estén ahí.

> i haces esta contribución y te interesa que te agregue al proyecto "primario" (con acceso de escritura al Git, pues).

Me gustaría, por que faltan 2 prácticas (si no me equivoco) por agregar, pero que no haré inmediatamente sino en el transcurso de la próxima semana.

Ahora mismo lo hago.
