### ISSUE TITLE
Ditaa da SIGSEGV en Debian 8

### ISSUE THREAD

**Issue by nwolovick** [gwolf/sistop#2]
Al hacer en Debian Testing

```
make fig_ditaaa
```

Se produce un `SIGSEGV` por parte de Java.
Lo solucioné de la siguiente manera

```
$ git diff Makefile
diff --git a/Makefile b/Makefile
index 1e45c78..aaae5da 100644
--- a/Makefile
+++ b/Makefile
@@ -217,7 +217,7 @@ DITAA_FIGS = $(wildcard fig/*.ditaa)
 DITAA_IMGS = $(patsubst fig/%.ditaa,img/ditaa/%.png,$(DITAA_FIGS))
 img/ditaa/%.png: fig/%.ditaa
        @[ -d img/ditaa ] || mkdir img/ditaa
-       java -jar /usr/share/ditaa/ditaa.jar -E -o $(patsubst img/ditaa/%.png,fig/%.ditaa,$@) $@
+       ditaa $(patsubst img/ditaa/%.png,fig/%.ditaa,$@) $@
 fig_ditaa: $(DITAA_IMGS)
 clean_ditaa:
        -rm -f $(DITAA_IMGS)
```

**Comment by gwolf** [comment]
Nicolás Wolovick dijo [Mon, Jun 15, 2015 at 07:54:36AM -0700]:

> Al hacer en Debian Testing
> 
> ```
> make fig_ditaaa
> ```
> 
> Se produce un `SIGSEGV` por parte de Java.
> Lo solucioné de la siguiente manera
> 
> ```
> $ git diff Makefile
> diff --git a/Makefile b/Makefile
> index 1e45c78..aaae5da 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -217,7 +217,7 @@ DITAA_FIGS = $(wildcard fig/*.ditaa)
>  DITAA_IMGS = $(patsubst fig/%.ditaa,img/ditaa/%.png,$(DITAA_FIGS))
>  img/ditaa/%.png: fig/%.ditaa
>         @[ -d img/ditaa ] || mkdir img/ditaa
> -       java -jar /usr/share/ditaa/ditaa.jar -E -o $(patsubst img/ditaa/%.png,fig/%.ditaa,$@) $@
> +       ditaa $(patsubst img/ditaa/%.png,fig/%.ditaa,$@) $@
>  fig_ditaa: $(DITAA_IMGS)
>  clean_ditaa:
>         -rm -f $(DITAA_IMGS)
> ```

Hmmm... Curioso. Más curioso, claro, la invocación de Java que estoy
haciendo — Supongo que habré tenido alguna razón para hacerlo de esta
manera.

Y sí: En mi lxc de wheezy, me parece que no está registrado el formato
binario de Java como ejecutable:

```
0 gwolf@wheezy『1』~$ ditaa vcs/sistemas_operativos/fig/acceso_aleatorio.ditaa -E -o /tmp/acceso_aleatorio.png
invalid file (bad magic number): Exec format error
1  gwolf@wheezy『2』~$ java -jar /usr/share/ditaa/ditaa.jar vcs/sistemas_operativos/fig/acceso_aleatorio.ditaa -E -o /tmp/acceso_aleatorio.png

ditaa version 0.9, Copyright (C) 2004--2009  Efstathios (Stathis) Sideris

Running with options:
no-separation
overwrite
Reading file: vcs/sistemas_operativos/fig/acceso_aleatorio.ditaa
Locale: en_US
Dialog.bold
Rendering to file: /tmp/acceso_aleatorio.png
Done in 1sec
0 gwolf@wheezy『4』~$
```

**Comment by nwolovick** [comment]
Luego de correr otro `jar` y que diera problemas, me topé con que es en realidad un problema de `openjdk-1.9.0`. Haciendo lo de abajo se soluciona. Cierro este _issue_.

```
update-java-alternatives -s java-1.7.0-openjdk-amd64
```

**Comment by gwolf** [comment]
Nicolás Wolovick dijo [Thu, Jun 18, 2015 at 06:39:11PM -0700]:

> Luego de correr otro `jar` y que diera problemas, me topé con que es en realidad un problema de `openjdk-1.9.0`. Haciendo lo de abajo se soluciona. Cierro este _issue_.
> 
> ```
> update-java-alternatives -s java-1.7.0-openjdk-amd64
> ```

¡Perfecto!
